const PLAYING_CARDS = [
    { name: 'back', label: 'back', path: 'public/tarot/back.jpg', default_count: 0 },
    { name: 'edge', label: 'edge', path: 'public/tarot/edge.jpg', default_count: 0 },
    { name: 'ace_of_clubs', label: 'Ace of Clubs', path: 'public/playing/ace_of_clubs.jpg', default_count: 1 },
    { name: 'ace_of_diamonds', label: 'Ace of Diamonds', path: 'public/playing/ace_of_diamonds.jpg', default_count: 1 },
    { name: 'ace_of_hearts', label: 'Ace of Hearts', path: 'public/playing/ace_of_hearts.jpg', default_count: 1 },
    { name: 'ace_of_spades', label: 'Ace of Spades', path: 'public/playing/ace_of_spades.jpg', default_count: 1 },
    { name: 'two_of_clubs', label: 'Two of Clubs', path: 'public/playing/two_of_clubs.jpg', default_count: 1 },
    { name: 'two_of_diamonds', label: 'Two of Diamonds', path: 'public/playing/two_of_diamonds.jpg', default_count: 1 },
    { name: 'two_of_hearts', label: 'Two of Hearts', path: 'public/playing/two_of_hearts.jpg', default_count: 1 },
    { name: 'two_of_spades', label: 'Two of Spades', path: 'public/playing/two_of_spades.jpg', default_count: 1 },
    { name: 'three_of_clubs', label: 'Three of Clubs', path: 'public/playing/three_of_clubs.jpg', default_count: 1 },
    { name: 'three_of_diamonds', label: 'Three of Diamonds', path: 'public/playing/three_of_diamonds.jpg', default_count: 1 },
    { name: 'three_of_hearts', label: 'Three of Hearts', path: 'public/playing/three_of_hearts.jpg', default_count: 1 },
    { name: 'three_of_spades', label: 'Three of Spades', path: 'public/playing/three_of_spades.jpg', default_count: 1 },
    { name: 'four_of_clubs', label: 'Four of Clubs', path: 'public/playing/four_of_clubs.jpg', default_count: 1 },
    { name: 'four_of_diamonds', label: 'Four of Diamonds', path: 'public/playing/four_of_diamonds.jpg', default_count: 1 },
    { name: 'four_of_hearts', label: 'Four of Hearts', path: 'public/playing/four_of_hearts.jpg', default_count: 1 },
    { name: 'four_of_spades', label: 'Four of Spades', path: 'public/playing/four_of_spades.jpg', default_count: 1 },
    { name: 'five_of_clubs', label: 'Five of Clubs', path: 'public/playing/five_of_clubs.jpg', default_count: 1 },
    { name: 'five_of_diamonds', label: 'Five of Diamonds', path: 'public/playing/five_of_diamonds.jpg', default_count: 1 },
    { name: 'five_of_hearts', label: 'Five of Hearts', path: 'public/playing/five_of_hearts.jpg', default_count: 1 },
    { name: 'five_of_spades', label: 'Five of Spades', path: 'public/playing/five_of_spades.jpg', default_count: 1 },
    { name: 'six_of_clubs', label: 'Six of Clubs', path: 'public/playing/six_of_clubs.jpg', default_count: 1 },
    { name: 'six_of_diamonds', label: 'Six of Diamonds', path: 'public/playing/six_of_diamonds.jpg', default_count: 1 },
    { name: 'six_of_hearts', label: 'Six of Hearts', path: 'public/playing/six_of_hearts.jpg', default_count: 1 },
    { name: 'six_of_spades', label: 'Six of Spades', path: 'public/playing/six_of_spades.jpg', default_count: 1 },
    { name: 'seven_of_clubs', label: 'Seven of Clubs', path: 'public/playing/seven_of_clubs.jpg', default_count: 1 },
    { name: 'seven_of_diamonds', label: 'Seven of Diamonds', path: 'public/playing/seven_of_diamonds.jpg', default_count: 1 },
    { name: 'seven_of_hearts', label: 'Seven of Hearts', path: 'public/playing/seven_of_hearts.jpg', default_count: 1 },
    { name: 'seven_of_spades', label: 'Seven of Spades', path: 'public/playing/seven_of_spades.jpg', default_count: 1 },
    { name: 'eight_of_clubs', label: 'Eight of Clubs', path: 'public/playing/eight_of_clubs.jpg', default_count: 1 },
    { name: 'eight_of_diamonds', label: 'Eight of Diamonds', path: 'public/playing/eight_of_diamonds.jpg', default_count: 1 },
    { name: 'eight_of_hearts', label: 'Eight of Hearts', path: 'public/playing/eight_of_hearts.jpg', default_count: 1 },
    { name: 'eight_of_spades', label: 'Eight of Spades', path: 'public/playing/eight_of_spades.jpg', default_count: 1 },
    { name: 'nine_of_clubs', label: 'Nine of Clubs', path: 'public/playing/nine_of_clubs.jpg', default_count: 1 },
    { name: 'nine_of_diamonds', label: 'Nine of Diamonds', path: 'public/playing/nine_of_diamonds.jpg', default_count: 1 },
    { name: 'nine_of_hearts', label: 'Nine of Hearts', path: 'public/playing/nine_of_hearts.jpg', default_count: 1 },
    { name: 'nine_of_spades', label: 'Nine of Spades', path: 'public/playing/nine_of_spades.jpg', default_count: 1 },
    { name: 'ten_of_clubs', label: 'Ten of Clubs', path: 'public/playing/ten_of_clubs.jpg', default_count: 1 },
    { name: 'ten_of_diamonds', label: 'Ten of Diamonds', path: 'public/playing/ten_of_diamonds.jpg', default_count: 1 },
    { name: 'ten_of_hearts', label: 'Ten of Hearts', path: 'public/playing/ten_of_hearts.jpg', default_count: 1 },
    { name: 'ten_of_spades', label: 'Ten of Spades', path: 'public/playing/ten_of_spades.jpg', default_count: 1 },
    { name: 'jack_of_clubs', label: 'Jack of Clubs', path: 'public/playing/jack_of_clubs.jpg', default_count: 1 },
    { name: 'jack_of_diamonds', label: 'Jack of Diamonds', path: 'public/playing/jack_of_diamonds.jpg', default_count: 1 },
    { name: 'jack_of_hearts', label: 'Jack of Hearts', path: 'public/playing/jack_of_hearts.jpg', default_count: 1 },
    { name: 'jack_of_spades', label: 'Jack of Spades', path: 'public/playing/jack_of_spades.jpg', default_count: 1 },
    { name: 'queen_of_clubs', label: 'Queen of Clubs', path: 'public/playing/queen_of_clubs.jpg', default_count: 1 },
    { name: 'queen_of_diamonds', label: 'Queen of Diamonds', path: 'public/playing/queen_of_diamonds.jpg', default_count: 1 },
    { name: 'queen_of_hearts', label: 'Queen of Hearts', path: 'public/playing/queen_of_hearts.jpg', default_count: 1 },
    { name: 'queen_of_spades', label: 'Queen of Spades', path: 'public/playing/queen_of_spades.jpg', default_count: 1 },
    { name: 'king_of_clubs', label: 'King of Clubs', path: 'public/playing/king_of_clubs.jpg', default_count: 1 },
    { name: 'king_of_diamonds', label: 'King of Diamonds', path: 'public/playing/king_of_diamonds.jpg', default_count: 1 },
    { name: 'king_of_hearts', label: 'King of Hearts', path: 'public/playing/king_of_hearts.jpg', default_count: 1 },
    { name: 'king_of_spades', label: 'King of Spades', path: 'public/playing/king_of_spades.jpg', default_count: 1 },
    { name: 'joker', label: 'Joker', path: 'public/playing/joker.jpg', default_count: 2 },
];

const TAROT_CARDS = [
    { name: 'back', label: 'back', path: 'public/tarot/back.jpg', default_count: 0 },
    { name: 'edge', label: 'edge', path: 'public/tarot/edge.jpg', default_count: 0 },
    { name: '0_the_fool', label: '0. The Fool', path: 'public/tarot/0_the_fool.jpg', default_count: 1 },
    { name: '10_whell_of_fortune', label: '10. Whell Of Fortune', path: 'public/tarot/10_whell_of_fortune.jpg', default_count: 1 },
    { name: '11_justice', label: '11. Justice', path: 'public/tarot/11_justice.jpg', default_count: 1 },
    { name: '12_the_hanged_man', label: '12. The Hanged Man', path: 'public/tarot/12_the_hanged_man.jpg', default_count: 1 },
    { name: '13_death', label: '13. Death', path: 'public/tarot/13_death.jpg', default_count: 1 },
    { name: '14_temperance', label: '14. Temperance', path: 'public/tarot/14_temperance.jpg', default_count: 1 },
    { name: '15_the_devil', label: '15. The Devil', path: 'public/tarot/15_the_devil.jpg', default_count: 1 },
    { name: '16_the_tower', label: '16. The Tower', path: 'public/tarot/16_the_tower.jpg', default_count: 1 },
    { name: '17_the_star', label: '17. The Star', path: 'public/tarot/17_the_star.jpg', default_count: 1 },
    { name: '18_the_moon', label: '18. The Moon', path: 'public/tarot/18_the_moon.jpg', default_count: 1 },
    { name: '19_the_sun', label: '19. The Sun', path: 'public/tarot/19_the_sun.jpg', default_count: 1 },
    { name: '1_the_magician', label: '1. The Magician', path: 'public/tarot/1_the_magician.jpg', default_count: 1 },
    { name: '20_judgement', label: '20. Judgement', path: 'public/tarot/20_judgement.jpg', default_count: 1 },
    { name: '21_the_world', label: '21. The World', path: 'public/tarot/21_the_world.jpg', default_count: 1 },
    { name: '2_the_high_priestess', label: '2. The High Priestess', path: 'public/tarot/2_the_high_priestess.jpg', default_count: 1 },
    { name: '3_the_empress', label: '3. The Empress', path: 'public/tarot/3_the_empress.jpg', default_count: 1 },
    { name: '4_the_emperor', label: '4. The Emperor', path: 'public/tarot/4_the_emperor.jpg', default_count: 1 },
    { name: '5_the_hierophant', label: '5. The Hierophant', path: 'public/tarot/5_the_hierophant.jpg', default_count: 1 },
    { name: '6_the_lovers', label: '6. The Lovers', path: 'public/tarot/6_the_lovers.jpg', default_count: 1 },
    { name: '7_the_chariot', label: '7. The Chariot', path: 'public/tarot/7_the_chariot.jpg', default_count: 1 },
    { name: '8_strength', label: '8. Strength', path: 'public/tarot/8_strength.jpg', default_count: 1 },
    { name: '9_the_hermit', label: '9. The Hermit', path: 'public/tarot/9_the_hermit.jpg', default_count: 1 },
    { name: 'ace_of_cups', label: 'Ace of Cups', path: 'public/tarot/ace_of_cups.jpg', default_count: 1 },
    { name: 'ace_of_pentacles', label: 'Ace of Pentacles', path: 'public/tarot/ace_of_pentacles.jpg', default_count: 1 },
    { name: 'ace_of_swords', label: 'Ace of Swords', path: 'public/tarot/ace_of_swords.jpg', default_count: 1 },
    { name: 'ace_of_wands', label: 'Ace of Wands', path: 'public/tarot/ace_of_wands.jpg', default_count: 1 },
    { name: 'eight_of_cups', label: 'Eight of Cups', path: 'public/tarot/eight_of_cups.jpg', default_count: 1 },
    { name: 'eight_of_pentacles', label: 'Eight of Pentacles', path: 'public/tarot/eight_of_pentacles.jpg', default_count: 1 },
    { name: 'eight_of_swords', label: 'Eight of Swords', path: 'public/tarot/eight_of_swords.jpg', default_count: 1 },
    { name: 'eight_of_wands', label: 'Eight of Wands', path: 'public/tarot/eight_of_wands.jpg', default_count: 1 },
    { name: 'five_of_cups', label: 'Five of Cups', path: 'public/tarot/five_of_cups.jpg', default_count: 1 },
    { name: 'five_of_pentacles', label: 'Five of Pentacles', path: 'public/tarot/five_of_pentacles.jpg', default_count: 1 },
    { name: 'five_of_swords', label: 'Five of Swords', path: 'public/tarot/five_of_swords.jpg', default_count: 1 },
    { name: 'five_of_wands', label: 'Five of Wands', path: 'public/tarot/five_of_wands.jpg', default_count: 1 },
    { name: 'four_of_cups', label: 'Four of Cups', path: 'public/tarot/four_of_cups.jpg', default_count: 1 },
    { name: 'four_of_pentacles', label: 'Four of Pentacles', path: 'public/tarot/four_of_pentacles.jpg', default_count: 1 },
    { name: 'four_of_swords', label: 'Four of Swords', path: 'public/tarot/four_of_swords.jpg', default_count: 1 },
    { name: 'four_of_wands', label: 'Four of Wands', path: 'public/tarot/four_of_wands.jpg', default_count: 1 },
    { name: 'king_of_cups', label: 'King of Cups', path: 'public/tarot/king_of_cups.jpg', default_count: 1 },
    { name: 'king_of_pentacles', label: 'King of Pentacles', path: 'public/tarot/king_of_pentacles.jpg', default_count: 1 },
    { name: 'king_of_swords', label: 'King of Swords', path: 'public/tarot/king_of_swords.jpg', default_count: 1 },
    { name: 'king_of_wands', label: 'King of Wands', path: 'public/tarot/king_of_wands.jpg', default_count: 1 },
    { name: 'knight_of_cups', label: 'Knight of Cups', path: 'public/tarot/knight_of_cups.jpg', default_count: 1 },
    { name: 'knight_of_pentacles', label: 'Knight of Pentacles', path: 'public/tarot/knight_of_pentacles.jpg', default_count: 1 },
    { name: 'knight_of_swords', label: 'Knight of Swords', path: 'public/tarot/knight_of_swords.jpg', default_count: 1 },
    { name: 'knight_of_wands', label: 'Knight of Wands', path: 'public/tarot/knight_of_wands.jpg', default_count: 1 },
    { name: 'nine_of_cups', label: 'Nine of Cups', path: 'public/tarot/nine_of_cups.jpg', default_count: 1 },
    { name: 'nine_of_pentacles', label: 'Nine of Pentacles', path: 'public/tarot/nine_of_pentacles.jpg', default_count: 1 },
    { name: 'nine_of_swords', label: 'Nine of Swords', path: 'public/tarot/nine_of_swords.jpg', default_count: 1 },
    { name: 'nine_of_wands', label: 'Nine of Wands', path: 'public/tarot/nine_of_wands.jpg', default_count: 1 },
    { name: 'page_of_cups', label: 'Page of Cups', path: 'public/tarot/page_of_cups.jpg', default_count: 1 },
    { name: 'page_of_pentacles', label: 'Page of Pentacles', path: 'public/tarot/page_of_pentacles.jpg', default_count: 1 },
    { name: 'page_of_swords', label: 'Page of Swords', path: 'public/tarot/page_of_swords.jpg', default_count: 1 },
    { name: 'page_of_wands', label: 'Page of Wands', path: 'public/tarot/page_of_wands.jpg', default_count: 1 },
    { name: 'queen_of_cups', label: 'Queen of Cups', path: 'public/tarot/queen_of_cups.jpg', default_count: 1 },
    { name: 'queen_of_pentacles', label: 'Queen of Pentacles', path: 'public/tarot/queen_of_pentacles.jpg', default_count: 1 },
    { name: 'queen_of_swords', label: 'Queen of Swords', path: 'public/tarot/queen_of_swords.jpg', default_count: 1 },
    { name: 'queen_of_wands', label: 'Queen of Wands', path: 'public/tarot/queen_of_wands.jpg', default_count: 1 },
    { name: 'seven_of_cups', label: 'Seven of Cups', path: 'public/tarot/seven_of_cups.jpg', default_count: 1 },
    { name: 'seven_of_pentacles', label: 'Seven of Pentacles', path: 'public/tarot/seven_of_pentacles.jpg', default_count: 1 },
    { name: 'seven_of_swords', label: 'Seven of Swords', path: 'public/tarot/seven_of_swords.jpg', default_count: 1 },
    { name: 'seven_of_wands', label: 'Seven of Wands', path: 'public/tarot/seven_of_wands.jpg', default_count: 1 },
    { name: 'six_of_cups', label: 'Six of Cups', path: 'public/tarot/six_of_cups.jpg', default_count: 1 },
    { name: 'six_of_pentacles', label: 'Six of Pentacles', path: 'public/tarot/six_of_pentacles.jpg', default_count: 1 },
    { name: 'six_of_swords', label: 'Six of Swords', path: 'public/tarot/six_of_swords.jpg', default_count: 1 },
    { name: 'six_of_wands', label: 'Six of Wands', path: 'public/tarot/six_of_wands.jpg', default_count: 1 },
    { name: 'ten_of_cups', label: 'Ten of Cups', path: 'public/tarot/ten_of_cups.jpg', default_count: 1 },
    { name: 'ten_of_pentacles', label: 'Ten of Pentacles', path: 'public/tarot/ten_of_pentacles.jpg', default_count: 1 },
    { name: 'ten_of_swords', label: 'Ten of Swords', path: 'public/tarot/ten_of_swords.jpg', default_count: 1 },
    { name: 'ten_of_wands', label: 'Ten of Wands', path: 'public/tarot/ten_of_wands.jpg', default_count: 1 },
    { name: 'three_of_cups', label: 'Three of Cups', path: 'public/tarot/three_of_cups.jpg', default_count: 1 },
    { name: 'three_of_pentacles', label: 'Three of Pentacles', path: 'public/tarot/three_of_pentacles.jpg', default_count: 1 },
    { name: 'three_of_swords', label: 'Three of Swords', path: 'public/tarot/three_of_swords.jpg', default_count: 1 },
    { name: 'three_of_wands', label: 'Three of Wands', path: 'public/tarot/three_of_wands.jpg', default_count: 1 },
    { name: 'two_of_cups', label: 'Two of Cups', path: 'public/tarot/two_of_cups.jpg', default_count: 1 },
    { name: 'two_of_pentacles', label: 'Two of Pentacles', path: 'public/tarot/two_of_pentacles.jpg', default_count: 1 },
    { name: 'two_of_swords', label: 'Two of Swords', path: 'public/tarot/two_of_swords.jpg', default_count: 1 },
    { name: 'two_of_wands', label: 'Two of Wands', path: 'public/tarot/two_of_wands.jpg', default_count: 1 },
];

const CardTypes = {
    PLAYING_CARDS: 'PLAYING_CARDS',
    TAROT_CARDS: 'TAROT_CARDS',
};

const CardDB = {
    [TYPES.PLAYING_CARDS]: PLAYING_CARDS,
    [TYPES.TAROT_CARDS]: TAROT_CARDS,
};

export { CardTypes, CardDB };